/* Local COREX catalog seed used only to bootstrap MockAPI when Product is empty. */
window.COREX_CATALOG_SEED = [
  // ==========================================
  // 1. WOMEN TAB PRODUCTS (ID 1-10)
  // ==========================================
  {
    id: 1,
    name: "CoreX Essential Sports Bra",
    category: "Yoga",
    subCategory: "Sports Bra",
    gender: "women",
    price: 32,
    oldPrice: null,
    rating: 4.8,
    reviews: 128,
    colors: [
      { name: "Mauve", value: "#B89EA6" },
      { name: "Black", value: "#222222" }
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "78% Nylon, 22% Spandex",
    image: "bra",
    imageUrl: "images/generated/women-corex-essential-sports-bra.png",
    imageQuality: "catalog",
    imageType: "women-yoga",
    alt: "Premium sports bra with medium support straps.",
    galleryImages: ["images/generated/women-corex-essential-sports-bra.png"],
    description: "Medium support sports bra designed for yoga, pilates and everyday movement. Soft, breathable and sweat-wicking.",
    features: ["Medium Support", "Sweat Wicking", "4-Way Stretch", "Removable Pads"],
    isBestSeller: true,
    badge: "Best Seller"
  },
  {
    id: 2,
    name: "CoreX Flow Leggings",
    category: "Yoga",
    subCategory: "Leggings",
    gender: "women",
    price: 45,
    oldPrice: null,
    rating: 4.9,
    reviews: 96,
    colors: [
      { name: "Mauve", value: "#B89EA6" },
      { name: "Black", value: "#222222" }
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "80% Recycled Polyester, 20% Elastane",
    image: "leggings",
    imageUrl: "images/generated/women-corex-flow-leggings.png",
    imageQuality: "catalog",
    imageType: "women-bottom",
    alt: "Model standing wearing premium high-waisted ribbed leggings.",
    galleryImages: ["images/generated/women-corex-flow-leggings.png"],
    description: "Our buttery-soft leggings feature a high-rise waist and minimal seams to keep you focused on your flow.",
    features: ["High Waisted", "4-Way Stretch", "Breathable", "Eco Friendly"],
    isBestSeller: true,
    badge: "Best Seller"
  },

  {
    id: 4,
    name: "CoreX Seamless Leggings",
    category: "Yoga",
    subCategory: "Leggings",
    gender: "women",
    price: 46,
    oldPrice: null,
    rating: 4.8,
    reviews: 66,
    colors: [
      { name: "Dark Grey", value: "#5D6A75" },
      { name: "Black", value: "#222222" }
    ],
    sizes: ["S", "M", "L"],
    material: "90% Nylon, 10% Elastane",
    image: "rib-leggings",
    imageUrl: "images/women_4.png",
    imageQuality: "catalog",
    imageType: "women-bottom",
    alt: "Model standing in ribbed activewear leggings.",
    galleryImages: ["images/women_4.png"],
    description: "Experience zero distractions with our seamless ribbed leggings, providing contoured support and targeted compression.",
    features: ["Seamless Design", "Sweat Wicking", "High Support", "4-Way Stretch"],
    isBestSeller: true,
    badge: "Best Seller"
  },
  {
    id: 5,
    name: "CoreX Open Back Bra",
    category: "Yoga",
    subCategory: "Sports Bra",
    gender: "women",
    price: 46,
    oldPrice: null,
    rating: 4.6,
    reviews: 40,
    colors: [
      { name: "Black", value: "#222222" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "78% Nylon, 22% Spandex",
    image: "bra",
    imageUrl: "images/women_5.png",
    imageQuality: "catalog",
    imageType: "women-yoga",
    alt: "Premium open back sports bra.",
    galleryImages: ["images/women_5.png"],
    description: "Stylish open back sports bra designed for hot yoga sessions and everyday athletic wear.",
    features: ["Open Back", "Medium Support", "Removable Pads", "Sweat Wicking"],
    badge: null
  },
  {
    id: 6,
    name: "CoreX Crop Top",
    category: "Yoga",
    subCategory: "Tops",
    gender: "women",
    price: 32,
    oldPrice: null,
    rating: 4.7,
    reviews: 58,
    colors: [
      { name: "Black", value: "#222222" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "92% Modal, 8% Spandex",
    image: "tank",
    imageUrl: "images/women_6.png",
    imageQuality: "catalog",
    imageType: "women-top",
    alt: "Activewear crop top.",
    galleryImages: ["images/women_6.png"],
    description: "Form-fitting crop top with minimal seams and sweat-wicking knit to keep you feeling cool.",
    features: ["Cropped Fit", "Sweat Wicking", "High Stretch"],
    badge: null
  },
  {
    id: 7,
    name: "CoreX High Waist Leggings",
    category: "Yoga",
    subCategory: "Leggings",
    gender: "women",
    price: 44,
    oldPrice: null,
    rating: 4.8,
    reviews: 82,
    colors: [
      { name: "Blue", value: "#4A6B82" }
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "80% Recycled Polyester, 20% Elastane",
    image: "leggings",
    imageUrl: "images/women_7.png",
    imageQuality: "catalog",
    imageType: "women-bottom",
    alt: "Model wearing premium high-waisted leggings.",
    galleryImages: ["images/women_7.png"],
    description: "High-waist leggings with compression fit for yoga classes or intense cardio routines.",
    features: ["High Waisted", "4-Way Stretch", "Eco Friendly"],
    isBestSeller: true,
    badge: "Best Seller"
  },
  {
    id: 8,
    name: "CoreX Performance Shorts",
    category: "Yoga",
    subCategory: "Shorts",
    gender: "women",
    price: 28,
    oldPrice: null,
    rating: 4.7,
    reviews: 45,
    colors: [
      { name: "Plum", value: "#5B3C46" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "88% Polyester, 12% Spandex",
    image: "shorts-w",
    imageUrl: "images/women_8.png",
    imageQuality: "catalog",
    imageType: "women-bottom",
    alt: "Model wearing gym training shorts.",
    galleryImages: ["images/women_8.png"],
    description: "Lightweight, breathable training shorts with a sweat-wicking liner and hidden pocket.",
    features: ["Sweat Wicking", "Inner Liner", "Waistband Pocket"],
    isBestSeller: true,
    badge: "Best Seller"
  },
  {
    id: 9,
    name: "CoreX Zip Jacket",
    category: "Yoga",
    subCategory: "Jackets",
    gender: "women",
    price: 58,
    oldPrice: null,
    rating: 4.6,
    reviews: 51,
    colors: [
      { name: "Beige", value: "#EFE7DF" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "85% Cotton, 15% Polyester",
    image: "jacket",
    imageUrl: "images/women_9.png",
    imageQuality: "catalog",
    imageType: "women-top",
    alt: "Premium zip-up activewear jacket.",
    galleryImages: ["images/women_9.png"],
    description: "Premium zip-up jacket made with breathable French Terry cotton for post-workout warmth.",
    features: ["Zip Closure", "French Terry", "Breathable"],
    badge: null
  },
  {
    id: 10,
    name: "CoreX Active Set",
    category: "Yoga",
    subCategory: "Set",
    gender: "women",
    price: 68,
    oldPrice: null,
    rating: 4.9,
    reviews: 62,
    colors: [
      { name: "Beige", value: "#EFE7DF" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "82% Nylon, 18% Spandex",
    image: "active-set",
    imageUrl: "images/new-arrivals/corex-active-set.png",
    imageQuality: "catalog",
    imageType: "women-yoga",
    alt: "Model wearing ribbed activewear matching set.",
    galleryImages: ["images/new-arrivals/corex-active-set.png"],
    description: "Matching ribbed activewear set. Includes sports bra and high-waisted seamless leggings.",
    features: ["Matching Set", "Seamless Ribbed", "High Waist"],
    badge: "New"
  },

  // ==========================================
  // 2. MEN TAB PRODUCTS (ID 11-20)
  // ==========================================
  {
    id: 11,
    name: "CoreX Performance Tee",
    category: "Gym",
    subCategory: "Tops",
    gender: "men",
    price: 28,
    oldPrice: null,
    rating: 4.8,
    reviews: 178,
    colors: [
      { name: "Slate Grey", value: "#5D6A75" }
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    material: "90% Polyester, 10% Spandex",
    image: "tee",
    imageUrl: "images/generated/men-corex-performance-tee.png",
    imageQuality: "catalog",
    imageType: "men-top",
    alt: "Male activewear gym t-shirt.",
    galleryImages: ["images/generated/men-corex-performance-tee.png"],
    description: "Engineered with anti-odor, sweat-wicking technology to keep you dry through heavy lifts.",
    features: ["Sweat Wicking", "Anti Odor", "Athletic Fit"],
    isBestSeller: true,
    badge: "Best Seller"
  },

  {
    id: 13,
    name: "CoreX Muscle Tank",
    category: "Gym",
    subCategory: "Tanks",
    gender: "men",
    price: 26,
    oldPrice: null,
    rating: 4.8,
    reviews: 65,
    colors: [
      { name: "Army Green", value: "#4A5D4E" }
    ],
    sizes: ["S", "M", "L", "XL"],
    material: "60% Cotton, 40% Polyester blend",
    image: "muscle-tank",
    imageUrl: "images/men_3.png",
    imageQuality: "catalog",
    imageType: "men-top",
    alt: "Male athlete posing in a gym tank.",
    galleryImages: ["images/men_3.png"],
    description: "Showcase your hard work. This muscle tank is made from an ultra-breathable cotton-poly blend.",
    features: ["Ultra Breathable", "Raw Armholes", "Soft Blend"],
    isBestSeller: true,
    badge: "Best Seller"
  },
  {
    id: 14,
    name: "CoreX Compression Tee",
    category: "Gym",
    subCategory: "Tops",
    gender: "men",
    price: 35,
    oldPrice: null,
    rating: 4.7,
    reviews: 98,
    colors: [
      { name: "White", value: "#FFFFFF" }
    ],
    sizes: ["S", "M", "L", "XL"],
    material: "85% Polyester, 15% Elastane",
    image: "compression",
    imageUrl: "images/men_4.png",
    imageQuality: "catalog",
    imageType: "men-top",
    alt: "Male athlete wearing tight compression shirt.",
    galleryImages: ["images/men_4.png"],
    description: "A second-skin compression top that wraps and supports major muscle groups, boosting circulation.",
    features: ["High Compression", "Muscular Support", "Quick Dry"],
    isBestSeller: true,
    badge: "Best Seller"
  },
  {
    id: 15,
    name: "CoreX Gym Shorts",
    category: "Gym",
    subCategory: "Shorts",
    gender: "men",
    price: 28,
    oldPrice: null,
    rating: 4.9,
    reviews: 140,
    colors: [
      { name: "Black", value: "#222222" }
    ],
    sizes: ["S", "M", "L", "XL"],
    material: "86% Recycled Nylon, 14% Spandex",
    image: "shorts-m",
    imageUrl: "images/men_5.png",
    imageQuality: "catalog",
    imageType: "men-bottom",
    alt: "Male runner wearing flexible training shorts.",
    galleryImages: ["images/men_5.png"],
    description: "Engineered for squats and sprints. Lightweight, breathable flex fabric features zip utility pockets.",
    features: ["Zip Pockets", "4-Way Stretch", "Side Vents"],
    isBestSeller: true,
    badge: "Best Seller"
  },
  {
    id: 16,
    name: "CoreX Training Pants",
    category: "Gym",
    subCategory: "Pants",
    gender: "men",
    price: 42,
    oldPrice: null,
    rating: 4.7,
    reviews: 102,
    colors: [
      { name: "Slate Grey", value: "#5D6A75" }
    ],
    sizes: ["S", "M", "L", "XL"],
    material: "88% Polyester, 12% Spandex",
    image: "joggers",
    imageUrl: "images/men_6.png",
    imageQuality: "catalog",
    imageType: "men-bottom",
    alt: "Male model standing in athletic jogger pants.",
    galleryImages: ["images/men_6.png"],
    description: "Tapered-leg joggers with dynamic knee articulation and zippered security pockets.",
    features: ["Tapered Fit", "Zip Pockets", "Drawcord Waist"],
    isBestSeller: true,
    badge: "Best Seller"
  },
  {
    id: 17,
    name: "CoreX Windbreaker",
    category: "Gym",
    subCategory: "Jackets",
    gender: "men",
    price: 88,
    oldPrice: null,
    rating: 4.8,
    reviews: 43,
    colors: [
      { name: "Black", value: "#222222" }
    ],
    sizes: ["S", "M", "L", "XL"],
    material: "100% Water-Resistant Nylon",
    image: "jacket",
    imageUrl: "images/men_7.png",
    imageQuality: "catalog",
    imageType: "men-top",
    alt: "Premium activewear windbreaker jacket.",
    galleryImages: ["images/men_7.png"],
    description: "Premium windbreaker jacket that offers lightweight protection against rain and wind during outdoor gym routines.",
    features: ["Water Resistant", "Wind Proof", "Zip Pockets"],
    badge: "Premium"
  },
  {
    id: 18,
    name: "CoreX 2-in-1 Shorts",
    category: "Gym",
    subCategory: "Shorts",
    gender: "men",
    price: 34,
    oldPrice: null,
    rating: 4.6,
    reviews: 57,
    colors: [
      { name: "Olive Green", value: "#4A5D4E" }
    ],
    sizes: ["S", "M", "L", "XL"],
    material: "86% Polyester, 14% Spandex with compression liner",
    image: "shorts-m",
    imageUrl: "images/men_8.png",
    imageQuality: "catalog",
    imageType: "men-bottom",
    alt: "Male activewear 2-in-1 training shorts.",
    galleryImages: ["images/men_8.png"],
    description: "Features a light outer layer and supportive built-in compression liner for maximum mobility.",
    features: ["Built-in Liner", "Sweat Wicking", "Phone Pocket"],
    badge: null
  },
  {
    id: 19,
    name: "CoreX Long Sleeve Tee",
    category: "Gym",
    subCategory: "Tops",
    gender: "men",
    price: 32,
    oldPrice: null,
    rating: 4.7,
    reviews: 61,
    colors: [
      { name: "Grey Marl", value: "#888888" }
    ],
    sizes: ["S", "M", "L", "XL"],
    material: "90% Polyester, 10% Spandex",
    image: "tee",
    imageUrl: "images/men_9.png",
    imageQuality: "catalog",
    imageType: "men-top",
    alt: "Male model in a long sleeve sports tee.",
    galleryImages: ["images/men_9.png"],
    description: "An athletic long sleeve shirt, perfect for warm-ups or cold-weather training sessions.",
    features: ["Thumbholes", "Thermal Control", "Quick Dry"],
    badge: null
  },
  {
    id: 20,
    name: "CoreX Active Set",
    category: "Gym",
    subCategory: "Set",
    gender: "men",
    price: 64,
    oldPrice: null,
    rating: 4.9,
    reviews: 35,
    colors: [
      { name: "Grey", value: "#888888" }
    ],
    sizes: ["S", "M", "L", "XL"],
    material: "90% Polyester, 10% Spandex",
    image: "active-set",
    imageUrl: "images/men_10.png",
    imageQuality: "catalog",
    imageType: "men-top",
    alt: "Male model wearing matching activewear set.",
    galleryImages: ["images/men_10.png"],
    description: "Coordinated activewear top and bottom set designed for serious workouts and gym sessions.",
    features: ["Matching Set", "Athletic Fit", "Breathable"],
    badge: "Popular"
  },

  // ==========================================
  // 3. YOGA TAB PRODUCTS (ID 21-30)
  // ==========================================
  {
    id: 21,
    name: "CoreX Yoga Tank Top",
    category: "Yoga",
    subCategory: "Tops",
    gender: "women",
    price: 26,
    oldPrice: null,
    rating: 4.7,
    reviews: 77,
    colors: [
      { name: "Off-White", value: "#FAF5F0" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "92% Modal, 8% Spandex",
    image: "tank",
    imageUrl: "images/generated/yoga-corex-yoga-tank-top.png",
    imageQuality: "catalog",
    imageType: "women-top",
    alt: "Woman wearing racerback yoga tank top.",
    galleryImages: ["images/generated/yoga-corex-yoga-tank-top.png"],
    description: "A lightweight, breathable tank top with a relaxed fit and dropped armholes.",
    features: ["Breathable", "Sweat Wicking", "Light Support"],
    isBestSeller: true,
    badge: "Best Seller"
  },
  {
    id: 22,
    name: "CoreX Seamless Leggings",
    category: "Yoga",
    subCategory: "Leggings",
    gender: "women",
    price: 46,
    oldPrice: null,
    rating: 4.8,
    reviews: 66,
    colors: [
      { name: "Grey Marl", value: "#888888" }
    ],
    sizes: ["S", "M", "L"],
    material: "90% Nylon, 10% Elastane",
    image: "rib-leggings",
    imageUrl: "images/generated/yoga-corex-seamless-leggings.png",
    imageQuality: "catalog",
    imageType: "women-bottom",
    alt: "Model standing in ribbed activewear leggings.",
    galleryImages: ["images/generated/yoga-corex-seamless-leggings.png"],
    description: "Experience zero distractions with our seamless ribbed leggings, providing contoured support.",
    features: ["Seamless Design", "High Support", "4-Way Stretch"],
    isBestSeller: true,
    badge: "Best Seller"
  },
  {
    id: 23,
    name: "CoreX Yoga Set",
    category: "Yoga",
    subCategory: "Set",
    gender: "women",
    price: 62,
    oldPrice: null,
    rating: 4.9,
    reviews: 51,
    colors: [
      { name: "Sage Green", value: "#A6BCA9" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "82% Nylon, 18% Spandex",
    image: "active-set",
    imageUrl: "images/yoga_3.png",
    imageQuality: "catalog",
    imageType: "women-yoga",
    alt: "Model wearing premium yoga matching set.",
    galleryImages: ["images/yoga_3.png"],
    description: "A matching set featuring medium support sports bra and high-waisted seamless leggings.",
    features: ["Matching Set", "Sage Green", "Soft Feeling"],
    isBestSeller: true,
    badge: "Best Seller"
  },
  {
    id: 24,
    name: "CoreX Longline Bra",
    category: "Yoga",
    subCategory: "Sports Bra",
    gender: "women",
    price: 32,
    oldPrice: null,
    rating: 4.7,
    reviews: 43,
    colors: [
      { name: "Blue", value: "#4A6B82" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "78% Nylon, 22% Spandex",
    image: "bra",
    imageUrl: "images/yoga_4.png",
    imageQuality: "catalog",
    imageType: "women-yoga",
    alt: "Premium blue longline sports bra.",
    galleryImages: ["images/yoga_4.png"],
    description: "Longline activewear bra offering high coverage and support for intensive yoga flows.",
    features: ["Longline Fit", "Medium Support", "Removable Pads"],
    isBestSeller: true,
    badge: "Best Seller"
  },

  {
    id: 26,
    name: "CoreX Ribbed Tank",
    category: "Yoga",
    subCategory: "Tops",
    gender: "women",
    price: 24,
    oldPrice: null,
    rating: 4.6,
    reviews: 38,
    colors: [
      { name: "Beige", value: "#EFE7DF" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "95% Modal, 5% Elastane",
    image: "tank",
    imageUrl: "images/yoga_6.png",
    imageQuality: "catalog",
    imageType: "women-top",
    alt: "Activewear ribbed tank top.",
    galleryImages: ["images/yoga_6.png"],
    description: "Soft ribbed tank top designed to stretch and move with your body.",
    features: ["Ribbed Texture", "High Stretch", "Comfort Fit"],
    badge: null
  },
  {
    id: 27,
    name: "CoreX High Waist Leggings",
    category: "Yoga",
    subCategory: "Leggings",
    gender: "women",
    price: 44,
    oldPrice: null,
    rating: 4.8,
    reviews: 56,
    colors: [
      { name: "Grey Marl", value: "#888888" }
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "80% Recycled Polyester, 20% Elastane",
    image: "leggings",
    imageUrl: "images/yoga_7.png",
    imageQuality: "catalog",
    imageType: "women-bottom",
    alt: "Model standing in high-waisted grey leggings.",
    galleryImages: ["images/yoga_7.png"],
    description: "High-waist leggings with moderate compression fit, ideal for yoga and meditation.",
    features: ["High Waisted", "Moderate Compression", "Breathable"],
    badge: null
  },
  {
    id: 28,
    name: "CoreX Yoga Shorts",
    category: "Yoga",
    subCategory: "Shorts",
    gender: "women",
    price: 28,
    oldPrice: null,
    rating: 4.7,
    reviews: 49,
    colors: [
      { name: "Sage Green", value: "#A6BCA9" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "88% Polyester, 12% Spandex",
    image: "shorts-w",
    imageUrl: "images/yoga_8.png",
    imageQuality: "catalog",
    imageType: "women-bottom",
    alt: "Model wearing sage green active shorts.",
    galleryImages: ["images/yoga_8.png"],
    description: "High-waisted yoga shorts with side pockets and a wide comfort waistband.",
    features: ["Side Pockets", "High Waisted", "4-Way Stretch"],
    badge: null
  },
  {
    id: 29,
    name: "CoreX Wrap Top",
    category: "Yoga",
    subCategory: "Tops",
    gender: "women",
    price: 30,
    oldPrice: null,
    rating: 4.8,
    reviews: 35,
    colors: [
      { name: "Beige", value: "#EFE7DF" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "92% Modal, 8% Spandex",
    image: "tank",
    imageUrl: "images/yoga_9.png",
    imageQuality: "catalog",
    imageType: "women-top",
    alt: "Model wearing premium wrap top.",
    galleryImages: ["images/yoga_9.png"],
    description: "Elegant wrap top designed to layer beautifully over sports bras during warm-up.",
    features: ["Wrap Design", "Soft Fabric", "Long Sleeve"],
    badge: null
  },
  {
    id: 30,
    name: "CoreX Meditation Mat",
    category: "Yoga",
    subCategory: "Yoga Mat",
    gender: "unisex",
    price: 46,
    oldPrice: null,
    rating: 4.9,
    reviews: 78,
    colors: [
      { name: "Beige", value: "#EFE7DF" }
    ],
    sizes: ["One Size"],
    material: "Natural Cork & TPE",
    image: "mat",
    imageUrl: "images/yoga_10.png",
    imageQuality: "catalog",
    imageType: "accessory",
    alt: "Beige yoga and meditation mat.",
    galleryImages: ["images/yoga_10.png"],
    description: "Premium cork meditation and yoga mat providing excellent traction and grip.",
    features: ["Natural Cork", "Anti Slip", "Cushioned Base"],
    badge: "Premium"
  },

  // ==========================================
  // 4. ACCESSORIES TAB PRODUCTS (ID 31-40)
  // ==========================================
  {
    id: 31,
    name: "CoreX Yoga Mat (5mm)",
    category: "Accessories",
    subCategory: "Yoga Mat",
    gender: "unisex",
    price: 48,
    oldPrice: null,
    rating: 4.9,
    reviews: 175,
    colors: [
      { name: "Light Blue", value: "#B2C5D4" }
    ],
    sizes: ["One Size"],
    material: "Natural Rubber & Polyurethane",
    image: "mat",
    imageUrl: "images/accessories/corex-yoga-mat.png",
    imageQuality: "catalog",
    imageType: "accessory",
    alt: "Rolled up light blue yoga mat.",
    galleryImages: ["images/accessories/corex-yoga-mat.png"],
    description: "5mm of dense cushioned support. Texturized grip surface made from biodegradable natural rubber.",
    features: ["Premium Cushioning", "High Grip", "Carry Strap"],
    isBestSeller: true,
    badge: "Best Seller"
  },
  {
    id: 32,
    name: "CoreX Gym Backpack",
    category: "Accessories",
    subCategory: "Backpack",
    gender: "unisex",
    price: 58,
    oldPrice: null,
    rating: 4.8,
    reviews: 112,
    colors: [
      { name: "Black", value: "#222222" }
    ],
    sizes: ["One Size"],
    material: "Water-Resistant Cordura Nylon",
    image: "backpack",
    imageUrl: "images/accessories/corex-gym-backpack.png",
    imageQuality: "catalog",
    imageType: "accessory",
    alt: "Black gym backpack.",
    galleryImages: ["images/accessories/corex-gym-backpack.png"],
    description: "A water-resistant backpack featuring a dedicated laptop sleeve and shoe compartment.",
    features: ["Water Resistant", "Shoe Compartment", "Laptop Sleeve"],
    isBestSeller: true,
    badge: "Best Seller"
  },
  {
    id: 33,
    name: "CoreX Water Bottle",
    category: "Accessories",
    subCategory: "Bottle",
    gender: "unisex",
    price: 22,
    oldPrice: null,
    rating: 4.7,
    reviews: 90,
    colors: [
      { name: "Off-White", value: "#FAF5F0" }
    ],
    sizes: ["One Size"],
    material: "18/8 Food-Grade Stainless Steel",
    image: "bottle",
    imageUrl: "images/accessories/corex-water-bottle.png",
    imageQuality: "catalog",
    imageType: "accessory",
    alt: "Stainless steel water bottle.",
    galleryImages: ["images/accessories/corex-water-bottle.png"],
    description: "Double-wall vacuum insulated stainless steel water bottle. Keeps drinks cold for 24 hours.",
    features: ["Insulated", "Stainless Steel", "BPA Free"],
    isBestSeller: true,
    badge: "Best Seller"
  },
  {
    id: 34,
    name: "CoreX Yoga Strap",
    category: "Accessories",
    subCategory: "Strap",
    gender: "unisex",
    price: 18,
    oldPrice: null,
    rating: 4.6,
    reviews: 32,
    colors: [
      { name: "Beige", value: "#EFE7DF" }
    ],
    sizes: ["One Size"],
    material: "100% Durable Cotton",
    image: "bands",
    imageUrl: "images/accessories/corex-yoga-strap.png",
    imageQuality: "catalog",
    imageType: "accessory",
    alt: "Beige yoga strap.",
    galleryImages: ["images/accessories/corex-yoga-strap.png"],
    description: "Premium cotton yoga strap with metal D-ring buckle to assist with poses and flexibility.",
    features: ["Durable Cotton", "Metal D-Ring", "Flexibility Assist"],
    badge: null
  },
  {
    id: 35,
    name: "CoreX Yoga Block",
    category: "Accessories",
    subCategory: "Block",
    gender: "unisex",
    price: 18,
    oldPrice: null,
    rating: 4.7,
    reviews: 41,
    colors: [
      { name: "Beige", value: "#EFE7DF" }
    ],
    sizes: ["One Size"],
    material: "High-Density EVA Foam",
    image: "block",
    imageUrl: "images/accessories/corex-yoga-block.png",
    imageQuality: "catalog",
    imageType: "accessory",
    alt: "Beige yoga block.",
    galleryImages: ["images/accessories/corex-yoga-block.png"],
    description: "High-density EVA foam block providing support, height and alignment for yoga classes.",
    features: ["High Density", "Beveled Edges", "Lightweight"],
    badge: null
  },
  {
    id: 36,
    name: "CoreX Foam Roller",
    category: "Accessories",
    subCategory: "Roller",
    gender: "unisex",
    price: 28,
    oldPrice: null,
    rating: 4.8,
    reviews: 54,
    colors: [
      { name: "Black", value: "#222222" }
    ],
    sizes: ["One Size"],
    material: "High-Density EVA Foam with rigid core",
    image: "roller",
    imageUrl: "images/accessories/corex-foam-roller.png",
    imageQuality: "catalog",
    imageType: "accessory",
    alt: "Black foam roller.",
    galleryImages: ["images/accessories/corex-foam-roller.png"],
    description: "Trigger-point foam roller designed for deep tissue massage and muscle recovery post-workout.",
    features: ["Grid Surface", "Rigid Core", "Muscle Recovery"],
    isBestSeller: true,
    badge: "Best Seller"
  },
  {
    id: 37,
    name: "CoreX Resistance Band",
    category: "Accessories",
    subCategory: "Bands",
    gender: "unisex",
    price: 18,
    oldPrice: null,
    rating: 4.7,
    reviews: 66,
    colors: [
      { name: "Plum", value: "#5B3C46" }
    ],
    sizes: ["One Size"],
    material: "Fabric Elastic & Latex",
    image: "bands",
    imageUrl: "images/accessories/corex-resistance-band.png",
    imageQuality: "catalog",
    imageType: "accessory",
    alt: "Plum resistance band.",
    galleryImages: ["images/accessories/corex-resistance-band.png"],
    description: "Premium fabric resistance loop band that doesn't roll or slip, perfect for glute training.",
    features: ["Non-Slip Fabric", "Glute Activation", "Durable Stitches"],
    badge: null
  },
  {
    id: 38,
    name: "CoreX Cap",
    category: "Accessories",
    subCategory: "Cap",
    gender: "unisex",
    price: 18,
    oldPrice: null,
    rating: 4.5,
    reviews: 50,
    colors: [
      { name: "White", value: "#FFFFFF" }
    ],
    sizes: ["One Size"],
    material: "100% Quick-Dry Polyester",
    image: "cap",
    imageUrl: "images/accessories/corex-cap.png",
    imageQuality: "catalog",
    imageType: "accessory",
    alt: "White sports cap.",
    galleryImages: ["images/accessories/corex-cap.png"],
    description: "Lightweight, breathable sports cap with adjustable back strap and sweat-wicking band.",
    features: ["Quick Dry", "Adjustable Fit", "Reflective Detail"],
    badge: null
  },
  {
    id: 39,
    name: "CoreX Socks",
    category: "Accessories",
    subCategory: "Socks",
    gender: "unisex",
    price: 12,
    oldPrice: null,
    rating: 4.6,
    reviews: 29,
    colors: [
      { name: "White", value: "#FFFFFF" }
    ],
    sizes: ["S/M", "L/XL"],
    material: "80% Cotton, 18% Polyester, 2% Spandex",
    image: "socks",
    imageUrl: "images/accessories/corex-socks.png",
    imageQuality: "catalog",
    imageType: "accessory",
    alt: "White athletic socks.",
    galleryImages: ["images/accessories/corex-socks.png"],
    description: "Cushioned athletic crew socks with arch support and sweat-wicking ventilation panels.",
    features: ["Arch Support", "Cushioned Sole", "Sweat Wicking"],
    badge: null
  },
  {
    id: 40,
    name: "CoreX Towel",
    category: "Accessories",
    subCategory: "Towel",
    gender: "unisex",
    price: 16,
    oldPrice: null,
    rating: 4.7,
    reviews: 33,
    colors: [
      { name: "Grey", value: "#888888" }
    ],
    sizes: ["One Size"],
    material: "85% Polyester, 15% Nylon Microfiber",
    image: "towel",
    imageUrl: "images/accessories/corex-towel.png",
    imageQuality: "catalog",
    imageType: "accessory",
    alt: "Grey microfibre fitness towel.",
    galleryImages: ["images/accessories/corex-towel.png"],
    description: "Ultra-absorbent, quick-drying microfiber gym towel. Compact and lightweight for yoga sessions.",
    features: ["Microfiber", "Quick Dry", "Absorbent"],
    badge: null
  },

  // ==========================================
  // 5. NEW ARRIVAL TAB PRODUCTS (ID 41-50)
  // ==========================================
  {
    id: 41,
    name: "CoreX Elevate Zip Jacket",
    category: "Yoga",
    subCategory: "Jackets",
    gender: "women",
    price: 58,
    oldPrice: null,
    rating: 4.6,
    reviews: 54,
    colors: [
      { name: "Beige", value: "#EFE7DF" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "85% Cotton, 15% Polyester",
    image: "jacket",
    imageUrl: "images/new-arrivals/corex-elevate-zip-jacket.png",
    imageQuality: "catalog",
    imageType: "women-top",
    alt: "Beige activewear zip jacket.",
    galleryImages: ["images/new-arrivals/corex-elevate-zip-jacket.png"],
    description: "Throw it on post-flow. Made with breathable French Terry cotton for plush warmth.",
    features: ["Zip Closure", "French Terry", "Breathable"],
    isNewArrival: true,
    badge: "New"
  },
  {
    id: 42,
    name: "CoreX Sculpt Leggings",
    category: "Yoga",
    subCategory: "Leggings",
    gender: "women",
    price: 48,
    oldPrice: null,
    rating: 4.8,
    reviews: 31,
    colors: [
      { name: "Black", value: "#222222" }
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "80% Nylon, 20% Spandex",
    image: "leggings",
    imageUrl: "images/new-arrivals/corex-sculpt-leggings.png",
    imageQuality: "catalog",
    imageType: "women-bottom",
    alt: "Model standing wearing sculpt leggings.",
    galleryImages: ["images/new-arrivals/corex-sculpt-leggings.png"],
    description: "Body-sculpting leggings featuring raw edge seams and targeted high waistband support.",
    features: ["Body Sculpting", "High Waist", "Hidden Key Pocket"],
    isNewArrival: true,
    badge: "New"
  },
  {
    id: 43,
    name: "CoreX Air Tee",
    category: "Gym",
    subCategory: "Tops",
    gender: "men",
    price: 28,
    oldPrice: null,
    rating: 4.7,
    reviews: 42,
    colors: [
      { name: "White", value: "#FFFFFF" }
    ],
    sizes: ["S", "M", "L", "XL"],
    material: "90% Polyester, 10% Elastane",
    image: "tee",
    imageUrl: "images/new-arrivals/corex-air-tee.png",
    imageQuality: "catalog",
    imageType: "men-top",
    alt: "Male athletic tee shirt.",
    galleryImages: ["images/new-arrivals/corex-air-tee.png"],
    description: "Extremely lightweight and ventilated training t-shirt for maximum airflow during gym flow.",
    features: ["Mesh Vents", "Feather Weight", "Quick Dry"],
    isNewArrival: true,
    badge: "New"
  },
  {
    id: 44,
    name: "CoreX Hybrid Shorts",
    category: "Gym",
    subCategory: "Shorts",
    gender: "men",
    price: 32,
    oldPrice: null,
    rating: 4.6,
    reviews: 38,
    colors: [
      { name: "Olive Green", value: "#4A5D4E" }
    ],
    sizes: ["S", "M", "L", "XL"],
    material: "88% Recycled Nylon, 12% Spandex",
    image: "shorts-m",
    imageUrl: "images/new-arrivals/corex-hybrid-shorts.png",
    imageQuality: "catalog",
    imageType: "men-bottom",
    alt: "Male activewear hybrid shorts.",
    galleryImages: ["images/new-arrivals/corex-hybrid-shorts.png"],
    description: "Versatile gym shorts built with dry-fast hybrid fabric and zippered security pocket.",
    features: ["Hybrid Fabric", "Zip Pocket", "Water Repellent"],
    isNewArrival: true,
    badge: "New"
  },
  {
    id: 45,
    name: "CoreX Seamless Bra",
    category: "Yoga",
    subCategory: "Sports Bra",
    gender: "women",
    price: 34,
    oldPrice: null,
    rating: 4.7,
    reviews: 30,
    colors: [
      { name: "Mauve", value: "#B89EA6" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "78% Nylon, 22% Spandex",
    image: "bra",
    imageUrl: "images/new-arrivals/corex-seamless-bra.png",
    imageQuality: "catalog",
    imageType: "women-yoga",
    alt: "Seamless mauve sports bra.",
    galleryImages: ["images/new-arrivals/corex-seamless-bra.png"],
    description: "Seamless knitted activewear bra designed to eliminate skin chafing and rub during runs.",
    features: ["Seamless Knit", "Light Support", "Moisture Wicking"],
    isNewArrival: true,
    badge: "New"
  },

  {
    id: 47,
    name: "CoreX Cropped Hoodie",
    category: "Yoga",
    subCategory: "Jackets",
    gender: "women",
    price: 54,
    oldPrice: null,
    rating: 4.8,
    reviews: 47,
    colors: [
      { name: "Beige", value: "#EFE7DF" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "85% Cotton, 15% Polyester",
    image: "jacket",
    imageUrl: "images/new-arrivals/corex-cropped-hoodie.png",
    imageQuality: "catalog",
    imageType: "women-top",
    alt: "Cropped sports hoodie.",
    galleryImages: ["images/new-arrivals/corex-cropped-hoodie.png"],
    description: "Buttery-soft cropped pullover hoodie for quick throwing on after yoga session.",
    features: ["Cropped Hem", "French Terry", "Comfort Hood"],
    isNewArrival: true,
    badge: "New"
  },

  {
    id: 49,
    name: "CoreX Active Set",
    category: "Yoga",
    subCategory: "Set",
    gender: "women",
    price: 54,
    oldPrice: null,
    rating: 4.8,
    reviews: 32,
    colors: [
      { name: "Sage Green", value: "#A6BCA9" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "82% Nylon, 18% Spandex",
    image: "active-set",
    imageUrl: "images/generated/new-arrival-corex-active-set.png",
    imageQuality: "catalog",
    imageType: "women-yoga",
    alt: "Sage green matching set.",
    galleryImages: ["images/generated/new-arrival-corex-active-set.png"],
    description: "A beautiful matching activewear crop top and shorts set in sage green tone.",
    features: ["Matching Set", "Sage Green", "Ultra Lightweight"],
    isNewArrival: true,
    badge: "New"
  },
  {
    id: 50,
    name: "CoreX Performance Pants",
    category: "Gym",
    subCategory: "Pants",
    gender: "men",
    price: 44,
    oldPrice: null,
    rating: 4.7,
    reviews: 36,
    colors: [
      { name: "Black", value: "#222222" }
    ],
    sizes: ["S", "M", "L", "XL"],
    material: "88% Polyester, 12% Spandex",
    image: "joggers",
    imageUrl: "images/new-arrivals/corex-performance-pants.png",
    imageQuality: "catalog",
    imageType: "men-bottom",
    alt: "Male model in gym training pants.",
    galleryImages: ["images/new-arrivals/corex-performance-pants.png"],
    description: "High performance running pants with elastic waistband and zippered cuffs for easy adjust.",
    features: ["Zippered Cuffs", "Water Repellent", "Zip Pockets"],
    isNewArrival: true,
    badge: "New"
  },

  // ==========================================
  // 6. SALE TAB PRODUCTS (ID 51-60)
  // ==========================================
  {
    id: 51,
    name: "CoreX Sports Bra",
    category: "Yoga",
    subCategory: "Sports Bra",
    gender: "women",
    price: 25.60,
    oldPrice: 32.00,
    rating: 4.8,
    reviews: 128,
    colors: [
      { name: "Mauve", value: "#B89EA6" }
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "78% Nylon, 22% Spandex",
    image: "bra",
    imageUrl: "images/sale_1.png",
    imageQuality: "catalog",
    imageType: "women-yoga",
    alt: "Model wearing premium sports bra on sale.",
    galleryImages: ["images/sale_1.png"],
    description: "Medium support sports bra designed for yoga, pilates and everyday movement. Soft and breathable.",
    features: ["Medium Support", "Sweat Wicking", "Sale Item"],
    isSale: true,
    badge: "Sale"
  },
  {
    id: 52,
    name: "CoreX Leggings",
    category: "Yoga",
    subCategory: "Leggings",
    gender: "women",
    price: 36.00,
    oldPrice: 45.00,
    rating: 4.9,
    reviews: 96,
    colors: [
      { name: "Mauve", value: "#B89EA6" }
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "80% Recycled Polyester, 20% Elastane",
    image: "leggings",
    imageUrl: "images/sale_2.png",
    imageQuality: "catalog",
    imageType: "women-bottom",
    alt: "Model wearing premium leggings on sale.",
    galleryImages: ["images/sale_2.png"],
    description: "Our buttery-soft leggings feature a high-rise waist and minimal seams to keep you focused on flow.",
    features: ["High Waisted", "4-Way Stretch", "Sale Item"],
    isSale: true,
    badge: "Sale"
  },

  {
    id: 54,
    name: "CoreX Gym Shorts",
    category: "Gym",
    subCategory: "Shorts",
    gender: "men",
    price: 22.40,
    oldPrice: 28.00,
    rating: 4.9,
    reviews: 140,
    colors: [
      { name: "Black", value: "#222222" }
    ],
    sizes: ["S", "M", "L", "XL"],
    material: "86% Recycled Nylon, 14% Spandex",
    image: "shorts-m",
    imageUrl: "images/sale_4.png",
    imageQuality: "catalog",
    imageType: "men-bottom",
    alt: "Male training shorts on sale.",
    galleryImages: ["images/sale_4.png"],
    description: "Engineered for squats and sprints. Lightweight, breathable flex fabric features zip pockets.",
    features: ["Zip Pockets", "4-Way Stretch", "Sale Item"],
    isSale: true,
    badge: "Sale"
  },
  {
    id: 55,
    name: "CoreX Zip Jacket",
    category: "Yoga",
    subCategory: "Jackets",
    gender: "women",
    price: 40.60,
    oldPrice: 58.00,
    rating: 4.6,
    reviews: 51,
    colors: [
      { name: "Beige", value: "#EFE7DF" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "85% Cotton, 15% Polyester",
    image: "jacket",
    imageUrl: "images/sale_5.png",
    imageQuality: "catalog",
    imageType: "women-top",
    alt: "Zip activewear jacket on sale.",
    galleryImages: ["images/sale_5.png"],
    description: "Premium zip-up jacket made with breathable French Terry cotton for post-workout warmth.",
    features: ["Zip Closure", "French Terry", "Sale Item"],
    isSale: true,
    badge: "Sale"
  },
  {
    id: 56,
    name: "CoreX Yoga Set",
    category: "Yoga",
    subCategory: "Set",
    gender: "women",
    price: 49.60,
    oldPrice: 62.00,
    rating: 4.9,
    reviews: 51,
    colors: [
      { name: "Sage Green", value: "#A6BCA9" }
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "82% Nylon, 18% Spandex",
    image: "active-set",
    imageUrl: "images/sale_6.png",
    imageQuality: "catalog",
    imageType: "women-yoga",
    alt: "Matching active set on sale.",
    galleryImages: ["images/sale_6.png"],
    description: "A matching set featuring medium support sports bra and high-waisted seamless leggings.",
    features: ["Matching Set", "High Waist", "Sale Item"],
    isSale: true,
    badge: "Sale"
  },
  {
    id: 57,
    name: "CoreX Muscle Tank",
    category: "Gym",
    subCategory: "Tanks",
    gender: "men",
    price: 20.80,
    oldPrice: 26.00,
    rating: 4.8,
    reviews: 65,
    colors: [
      { name: "Army Green", value: "#4A5D4E" }
    ],
    sizes: ["S", "M", "L", "XL"],
    material: "60% Cotton, 40% Polyester blend",
    image: "muscle-tank",
    imageUrl: "images/sale_7.png",
    imageQuality: "catalog",
    imageType: "men-top",
    alt: "Athletic muscle tank on sale.",
    galleryImages: ["images/sale_7.png"],
    description: "Showcase your hard work. This muscle tank is made from an ultra-breathable cotton-poly blend.",
    features: ["Ultra Breathable", "Raw Armholes", "Sale Item"],
    isSale: true,
    badge: "Sale"
  },
  {
    id: 58,
    name: "CoreX Backpack",
    category: "Accessories",
    subCategory: "Backpack",
    gender: "unisex",
    price: 49.30,
    oldPrice: 58.00,
    rating: 4.8,
    reviews: 112,
    colors: [
      { name: "Black", value: "#222222" }
    ],
    sizes: ["One Size"],
    material: "Water-Resistant Cordura Nylon",
    image: "backpack",
    imageUrl: "images/sale_8.png",
    imageQuality: "catalog",
    imageType: "accessory",
    alt: "Gym backpack on sale.",
    galleryImages: ["images/sale_8.png"],
    description: "A water-resistant backpack featuring a dedicated laptop sleeve and shoe compartment.",
    features: ["Water Resistant", "Shoe Compartment", "Sale Item"],
    isSale: true,
    badge: "Sale"
  },
  {
    id: 59,
    name: "CoreX Yoga Mat",
    category: "Accessories",
    subCategory: "Yoga Mat",
    gender: "unisex",
    price: 38.40,
    oldPrice: 48.00,
    rating: 4.9,
    reviews: 175,
    colors: [
      { name: "Light Blue", value: "#B2C5D4" }
    ],
    sizes: ["One Size"],
    material: "Natural Rubber & Polyurethane",
    image: "mat",
    imageUrl: "images/sale_9.png",
    imageQuality: "catalog",
    imageType: "accessory",
    alt: "Premium yoga mat on sale.",
    galleryImages: ["images/sale_9.png"],
    description: "5mm of dense cushioned support. Texturized grip surface made from biodegradable natural rubber.",
    features: ["Premium Cushioning", "High Grip", "Sale Item"],
    isSale: true,
    badge: "Sale"
  },
  {
    id: 60,
    name: "CoreX Cap",
    category: "Accessories",
    subCategory: "Cap",
    gender: "unisex",
    price: 14.40,
    oldPrice: 18.00,
    rating: 4.5,
    reviews: 50,
    colors: [
      { name: "White", value: "#FFFFFF" }
    ],
    sizes: ["One Size"],
    material: "100% Quick-Dry Polyester",
    image: "cap",
    imageUrl: "images/accessories/corex-cap.png",
    imageQuality: "catalog",
    imageType: "accessory",
    alt: "Sports cap on sale.",
    galleryImages: ["images/sale_10.png"],
    description: "Lightweight, breathable sports cap with adjustable back strap and sweat-wicking band.",
    features: ["Quick Dry", "Adjustable Fit", "Sale Item"],
    isSale: true,
    badge: "Sale"
  }
];
